lenny_dict = {"regular": "( ͡° ͜ʖ ͡°)",
                "confused": "( ͠° ͟ʖ ͡°)",
                "strong": "ᕦ( ͡° ͜ʖ ͡°)ᕤ",
                "cat": "( ͡° ᴥ ͡°)",
                "wink": "( ͡~ ͜ʖ ͡°)",
                "swiggity": "( ͡o ͜ʖ ͡o)",
                "wink2": "( ͡° ͜ʖ ͡ -)",
                "alien": "( ͡ ͡° ͡° ʖ ͡° ͡°)",
                "uwotm8": "(ง ͠° ͟ل͜ ͡°)ง",
                "gang": "( ͡°( ͡° ͜ʖ( ͡° ͜ʖ ͡°)ʖ ͡°) ͡°)",
                "derp": "( ͡° ͜ʖ ͡ °)",
                "square": "[ ͡° ͜ʖ ͡°]",
                "impostor": "{ ͡• ͜ʖ ͡•}",
                "happy": "( ͡^ ͜ʖ ͡^)",
                "sensei": "( ͡°╭͜ʖ╮͡° )",
                "dollar": "[̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]",
                "noseless": "( ͡° ͜ ͡°)",
                "cool": "(⌐■_■)",
                "cheeky": "(͡o‿O͡)",
                "tableflip": "(╯°□°)╯︵ ┻━┻",
                "confused": "乁( ⁰͡ Ĺ̯ ⁰͡ ) ㄏ",
                "hay": "(◕ ◡ ◕)",
                "badass":  "̿ ̿'̿'\̵͇̿̿\з=(⌐■ʖ■)=ε/̵͇̿̿/'̿̿ ̿ ̿",
                "lurk": "┬┴┬┴┤( ͡° ͜ʖ├┬┴┬┴",
                "fingerguns": "(☞ ͡° ͜ʖ ͡°)☞",
                "wtf": "( ಠ ͟ʖ ಠ)",
                "wtf2": "(ノಠ益ಠ)ノ",
                "shrug": "¯\_(ツ)_/¯",
                "sad": "( ͡° ʖ̯ ͡°)"}

codesworth_lenny = lambda x: lenny_dict[x] if x in lenny_dict.keys() else "Lenny not found "+lenny_dict["sad"]

